/** @type {import('tailwindcss').Config} */

const colors = require("./src/greenbase-colors");

module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    fontFamily: {
      sans: ["Inter", "system-ui", "sans-serif"],
    },
    fontSize: {
      xs: ["0.75rem", { lineHeight: "1rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      "display-1": ["5rem", { lineHeight: "7rem" }],
      "display-2": ["4rem", { lineHeight: "5.625rem" }],
      "display-3": ["3rem", { lineHeight: "4.125rem" }],
      "display-4": ["2rem", { lineHeight: "2.75rem" }],
      "display-5": ["1.5rem", { lineHeight: "2.25rem" }],
      "display-6": ["1.25rem", { lineHeight: "1.75rem" }],
    },
    colors: {
      transparent: "transparent",
      white: "#FFFFFF",
      primary: "#1E5EFF",
      ["primary-hover"]: "#4F81FF",
      ["primary-active"]: "#336DFF",
      ["primary-focus"]: "#1E5EFF",
      secondary: "#D9E4FF",
      ["secondary-hover"]: "#ECF2FF",
      ["secondary-active"]: "#D9E4FF",
      ["secondary-focus"]: "#D9E4FF",
      destructive: "#F0142F",
      ["destructive-hover"]: "#F34359",
      ["destructive-active"]: "#F12B43",
      ["destructive-focus"]: "#F0142F",
      ["destructive-secondary"]: "#FDE7EA",
      ["destructive-secondary-hover"]: "#FCD5D9",
      ["destructive-secondary-active"]: "#FDE7EA",
      ["destructive-secondary-focus"]: "#FDE7EA",
      disabled: "#D7DBEC",
      main: "#131523",
      muted: "#5A607F",
      ["border-default"]: "#D7DBEC",
      background: "#F5F6FA",
      grey: {
        30: "#F5F6FA",
        40: "#E6E9F4",
        50: "#D7DBEC",
        60: "#A1A7C4",
        70: "#7E84A3",
        80: "#5A607F",
        90: "#333752",
        100: "#131523",
      },
      blue: {
        30: "#ECF2FF",
        40: "#D9E4FF",
        50: "#B6CBFF",
        60: "#89ABFF",
        70: "#608DFF",
        80: "#4F81FF",
        90: "#336DFF",
        100: "#1E5EFF",
      },
      purple: {
        30: "#ECF2FF",
        40: "#D9E4FF",
        50: "#B6CBFF",
        60: "#89ABFF",
        70: "#608DFF",
        80: "#4F81FF",
        90: "#336DFF",
        100: "#1E5EFF",
      },
      red: {
        30: "#FDE7EA",
        40: "#FCD5D9",
        50: "#FAB3BC",
        60: "#F8919D",
        70: "#F45A6D",
        80: "#F34359",
        90: "#F12B43",
        100: "#F0142F",
      },
      green: {
        30: "#DAF9EC",
        40: "#C4F8E2",
        50: "#95F6CC",
        60: "#74EFB9",
        70: "#48E9A5",
        80: "#25E191",
        90: "#1FD286",
        100: "#06A561",
      },
      yellow: {
        30: "#FFF9E1",
        40: "#FFF4C9",
        50: "#FFECA3",
        60: "#FFE582",
        70: "#FFE45F",
        80: "#FFD613",
        90: "#FFC700",
        100: "#F99600",
      },
    },
    spacing: {
      px: "1px",
      0: "0px",
      0.5: "0.125rem",
      1: "0.25rem",
      1.5: "0.375rem",
      2: "0.5rem",
      2.5: "0.625rem",
      3: "0.75rem",
      3.5: "0.875rem",
      4: "1rem",
      5: "1.25rem",
      6: "1.5rem",
      7: "1.75rem",
      8: "2rem",
    },
    extend: {
      textColor: {
        skin: {
          base: "var(--color-text-base)",
          muted: "var(--color-text-muted)",
          inverted: "var(--color-text-inverted)",
          primary: "var(--color-primary)",
          success: "var(--color-success)",
          destructive: "var(--color-destructive)",
        },
      },
      backgroundColor: {
        skin: {
          primary: "var(--color-primary)",
          success: "var(--color-success)",
          destructive: "var(--color-destructive)",
          secondary: "var(--color-primary-muted)",
          "success-secondary": "var(--color-success-muted)",
          "destructive-secondary": "var(--color-destructive-muted)",
          disabled: "var(--color-disabled)",
        },
      },
      borderColor: {
        skin: {
          border: "var(--color-border)",
          "border-primary": "var(--color-primary)",
          "border-destructive": "var(--color-destructive)",
          "border-success": "var(--color-success)",
          disabled: "var(--color-disabled)",
        },
      },
      colors: {
        skin: {
          "primary-hover": "var(--color-hover-primary)",
          "secondary-hover": "var(--color-hover-secondary)",
          "default-hover": "var(--color-hover-default)",
          "destructive-hover": "var(--color-hover-destructive)",
          "destructive-secondary-hover":
            "var(--color-hover-destructive-secondary)",
          "primary-active": "var(--color-active-primary)",
          "secondary-active": "var(--color-active-secondary)",
          "default-active": "var(--color-active-default)",
          "destructive-active": "var(--color-active-destructive)",
          "destructive-secondary-active":
            "var(--color-active-destructive-secondary)",
          "primary-focus": "var(--color-focus-primary)",
          "secondary-focus": "var(--color-focus-secondary)",
          "default-focus": "var(--color-focus-default)",
          "destructive-focus": "var(--color-focus-destructive)",
          "destructive-secondary-focus":
            "var(--color-focus-destructive-secondary)",
        },
      },
    },
  },
  plugins: [],
};
